### ISSUE TITLE
Unable to unlink AI, BI & Accumulator is fine.

### ISSUE THREAD

**Issue by CjLoo** [ADFTech/XTEC_UC_MSTP_Public#1]
![unable to unlink ai](https://user-images.githubusercontent.com/30944584/29237916-dbe2fe84-7f5a-11e7-9c4a-1d393fa67c1f.png)

@fakhrul-omar @kslee911

**Comment by fakhrul-omar** [comment]
Could you provide the log file, @CjLoo?

**Comment by CjLoo** [comment]
[logfile.txt](https://github.com/ADFTech/XTEC_UC_MSTP_Public/files/1221146/logfile.txt)

**Comment by fakhrul-omar** [comment]
Should be okay now with r2166c34. The boards already flashed with the patch are 1 old UI18 and 1 new UI22.

**Comment by CjLoo** [comment]
noted with thanks
